name: TestPlugin
main: io.github.joncmak.TestPlugin.PluginMain
version: 1.0
commands:
    testplugin.reload:
        description: Reload command
        usage: /<command>
        permission: TestPlugin.reload
    testplugin.block:
        description: Change broken block
        usage: /<command> <block>
        permission: TestPlugin.block
    testplugin.join:
        description: Change join message
        usage: /<command> <message>
        permission: TestPlugin.join
    testplugin.firstjoin:
        description: Change first join message
        usage: /<command> <message>
        permission: TestPlugin.firstjoin